### ISSUE TITLE
Is an app lock PIN / passphrase necessary?

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/phoneypot#25]
isn't the phone lock enough?

**Comment by n8fr8** [comment]
detect if there is security lock enabled on the phone, then maybe we need our own, or prompt them to add them.

**Comment by Serega-77** [comment]
https://drive.google.com/file/d/0Bwy_U5vs3AzXcHJHbWFHRm12Ums/view?usp=drivesdk

**Comment by Serega-77** [comment]
languach in ru?

**Comment by n8fr8** [comment]
The 0.0.3 build removes the pin lock for now. Will continue to consider how/when we might want to force the user to have one.
