### ISSUE TITLE
Can't trigger image events anymore, and sound events are repeated

### ISSUE THREAD

**Issue by micahflee** [guardianproject/phoneypot#26]
I've been testing out PhoneyPot 0.0.5, and I'm seeing some weird behavior. Inside my app there are currently 14 incidents. The first incident has 3 camera motion events, with 3 different images.

But the rest of the incidents only have sound events, and in fact I can't even get the app to register camera motion events at all. If I activate it and move a bunch in front of the camera, or pick up the phone, it doesn't register new camera motion events (or accelerometer events). It only registers sound events.

In the remaining 13 incidents, all of the sound events are the exact same audio file (the sound of emergency vehicle sirens driving by). It's a 14-second clip, and that same clip is listed for each event. Most of the incidents have only 1 event, but one incident has 4 different events, but those events are all the same 14-second sound clip of sirens.

Also, I can't always reproduce this one, but sometimes when I'm scrolling through the list of incidents, I can't scroll all the way to the bottom of the list, it just stops before the bottom so I can't click on the most recent items. Although that's not happening now. In any case, it would be helpful to reverse the order of the incidents, so that the most recent is at the top instead of at the bottom.

My test phone is a Nexus 5 running the latest version of LineageOS, without root. I'm happy to try to help debug by extracting data from my phone.

**Comment by n8fr8** [comment]
That is strange behavior. Perhaps the camera sensor was unavailable for some reason 

Reverse chrono order of the events is easy.

**Comment by micahflee** [comment]
I just noticed, in the root of my phone's filesystem there's `phoneypot.m4a` which is the audio of the siren. I also have a `phoneypot` folder, and it has a bunch of `jpg`s in it, I think most of which weren't displayed in the UI.
