### ISSUE TITLE
monitor change from camera sensor (both front and back)

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/phoneypot#3]
We'll have to see how the visual change detection works in different lighting

**Comment by n8fr8** [comment]
Currently, you choose whether you want front or back. I am not sure we can or want to do both.

**Comment by percy-g2** [comment]
https://github.com/percy-g2/haven/commits/dual-camera

i have got working monitor change from both camera's at the same time, selectable from settings FRONT,BACK,BOTH and NONE.
