### ISSUE TITLE
Unable to build on Android Studio 3

### ISSUE THREAD

**Issue by mrphs** [guardianproject/phoneypot#39]
I'm trying to build the apk for some testing but can't get it to work. I get 5 errors of Gradle saying it wasn't able to resolve resolve project `:external:signal-cli`. Is there something obvious I'm missing? Do I need to be using a specific version of Gradle or Android Studio?

**Comment by n8fr8** [comment]
Did you run: git submodule update --init --recursive to fetch the external dependency?

**Comment by n8fr8** [comment]
(We are still using git dependencies as we haven't published our version of signal-cli for android yet as a gradle module)

**Comment by mrphs** [comment]
Cool. I did that and it worked. Now I get this:

Unsupported Modules Detected: Compilation is not supported for following modules: phoneypot. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

It would be nice to have the steps to build it documented in the readme file for people who've not built an apk before. the git submodule one for example is counter-intuitive. I would be happy to volunteer to do that once I manage to make a working apk :)

**Comment by n8fr8** [comment]
Yeah, this project went for "let's hack on a prototype idea" to a real thing very quickly. As we are soon to make an announcement about it, we need to have all these details outlined. 

I haven't seen that error about the modules before. I will try to debug it.

The other approach we can take with the submodule is to move it to a gradle dependency, so that you don't need to take that step at all.

**Comment by n8fr8** [comment]
Okay, done. I removed signal-ci as a gitsubmodule, and switched it out for a gradle dependency.

https://github.com/guardianproject/phoneypot/commit/6db0bdfe4d75f21ca4c6a5bedf944db5917b1cb1
https://github.com/guardianproject/phoneypot/commit/d3d97d641b634eed83692c80e845e0af0b37ee5b

I also fixed the signal-cli-android gradle configuration to build properly as a standalone android library:
https://github.com/guardianproject/signal-cli-android/commits/master

**Comment by mrphs** [comment]
> Yeah, this project went for "let's hack on a prototype idea" to a real thing very quickly

I totally understand. That's why I wanted to check it out to see if I can help make it a really good prototype :)

> As we are soon to make an announcement about it, we need to have all these details outlined.

Please do let me know if there's anything I can do to help. I would love to see this project to become a success.

> Okay, done. I removed signal-ci as a gitsubmodule, and switched it out for a gradle dependency.

That did it for me! Thanks! 🙌🏽
